OBJS = error.o list.o main.o must.o normal.o parsetime.o quack.o time.o

CC = clang
CFLAGS = -DMACOS

quack: $(OBJS)
	$(CC) -o $@ $(OBJS)

%.o: %.c %.h
	$(CC) $(CFLAGS) -c $<

clean:
	/bin/rm -f $(OBJS)
